# 
FROM php:7.4-cli AS builder

WORKDIR /var/www

RUN apt-get update && \
  apt-get install libzip-dev -y && \
  docker-php-ext-install zip

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \  
  php composer-setup.php && \
  php -r "unlink('composer-setup.php');"

RUN php composer.phar create-project laravel/laravel laravel

# Trabalhando com Multistage Building

# Iniciando um novo processo
FROM php:7.4-fpm-alpine
WORKDIR /var/www
RUN rm -rf /var/www/html