version: "3"

services:
  laravel:
    build:
      context: ../multistage-building/laravel
      dockerfile: Dockerfile.prod
    image: higosampaio/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile.prod
    image: higosampaio/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge
