version: "3"

services:
  laravel:
    image: higosampaio/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: higosampaio/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge
